### ISSUE TITLE
Add Pi-hole (DNS & Network-wide Ad Blocking) docker container support

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#147]
Pi-hole is something I've been wanting to test out but haven't had the time. I think a containerized DNS server that does ad blocking is something everyone is going to want and Pi-hole seems to be "it."

https://hub.docker.com/r/pihole/pihole

**Comment by koenvervloesem** [comment]
I tested both Pi-hole and AdGuard Home (https://github.com/AdguardTeam/AdGuardHome) and I preferred the latter. It has more features out-of-the-box (there's a comparison table on the project's GitHub page) and I found the web interface easier to use.

**Comment by bcurran3** [comment]
Cool. Thanks. Never heard of it. On my RADAR now as that comparison chart is great at pointing out the features. It does have a docker container, https://hub.docker.com/r/adguard/adguardhome. I'd vote for both but am going to bump this one up on my personal list for testing.

**Comment by davestephens** [comment]
It's worth anyone interested in this reading #54. There are issues in supporting ad-blocking services as it's required to have 80/443 dedicated to them, which we can't do easily/simply due to Traefik.

**Comment by bcurran3** [comment]
RE: AdGuardHome - management via port 3000 will also conflict with Grafana.

Both Pi-hole and AdGuardHome have mentions of working via proxy. I'm sure it ads a lot of configuration overhead, but it looks doable. 

Maybe we can leave this open until someone can work through it and share (help wanted). If so, this issue can be renamed for AdGuardHome and the original Pi-hole issue could be re-opened.

**Comment by animeai** [comment]
@davestephens 
I'd have thought this would be best addressed by using bridged networking so the PiHole container has its own local IP address.

@bcurran3 The port 3000 conflict isn't an issue as you can map the external port separately to the internal port  in the container settings.

**Comment by davestephens** [comment]
Bridged networking doesn't solve the problem, sadly. The reasons are
detailed further up in this issue, but tl;dr; to work correctly ad blockers
need port 80 and 443 on the box you host the software on.

**Comment by bcurran3** [comment]
Looks like it IS possible:
https://www.smarthomebeginner.com/run-pihole-in-docker-on-ubuntu-with-reverse-proxy/

**Comment by ideologysec** [comment]
No reason it shouldn't work inside a container with bridged networking; piHole is really only doing its magic on port 53 (DNS); 80 and 443 are there for administration to my understanding.

**Comment by davestephens** [comment]
Port 80 and 443 absolutely are used for ad blocking. See
https://github.com/davestephens/ansible-nas/issues/54#issuecomment-488426062
for info.

Traefik internal ports were made configurable for this reason.

**Comment by ideologysec** [comment]
I stand corrected/knowledge-upgraded, especially after reading more of the docs. :)

**Comment by bcurran3** [comment]
I've got this done and working. Very happy about it. I'll submit a PR once I create the pihole_without_traefik task...

24 hour results:
![image](https://user-images.githubusercontent.com/14026600/81468379-0dbe8b00-9194-11ea-9670-6452cab9cc3b.png)

**Comment by nicpayne713** [comment]
What is the status of this request? This would be an awesome feature for me (and others) to be included in Ansible-NAS

**Comment by HitLuca** [comment]
@nicpayne713 if you want to have it and can live with doing a bit more work than setting `pihole_enabled: true` you can do it in portainer (the example uses the pihole-unbound image as it's what I use).

- make sure your nas has a static ip in your home network
- create a new stack in portainer
- set the name to whatever you want
- create a `pihole-unbound` directory where all your other applications config live (your `docker_home`)
- add this as docker-compose entry

```yaml
version: '2'

services:
  pihole:
    container_name: pihole-unbound
    image: cbcrowe/pihole-unbound:latest
    environment:
      FTLCONF_REPLY_ADDR4: ${FTLCONF_REPLY_ADDR4}
      TZ: ${TZ}
      WEB_PORT: ${WEB_PORT}
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: "true"
      INTERFACE: ${INTERFACE}
    volumes:
      - ${CONFIG_FOLDER}/etc-pihole:/etc/pihole:rw
      - ${CONFIG_FOLDER}/etc-dnsmasq:/etc/dnsmasq.d:rw
    restart: unless-stopped
    network_mode: host
    mem_limit: 1Gb
```
- in the environment variables section, add these lines

```raw
FTLCONF_REPLY_ADDR4=# your nas ip
TZ= # your TZ
CONFIG_FOLDER=# your `docker_home` full path /pihole-unbound
WEB_PORT=8182
INTERFACE=# i have enp4s0 here, if your network adapter has a different name use that
```

Deploy the stack, pihole won't work as it's trying to bind port 53. This is fine as we needed dns access when deploying the stack. shut down the `resolved` service on your nas with `sudo systemctl disable systemd-resolved` and `sudo systemctl stop systemd-resolved`. Restart the pihole container and it should now work, check out the ui page.

Now you can use pihole as dns resolver for all your network, just set your nas ip as primary dns server on your router page (and leave the secondary server set to 0.0.0.0). If you have connected devices just disconnect from the network and rejoin it to update the dns preferences

**Comment by nicpayne713** [comment]
Thanks @HitLuca , personally I decided to move pi-hole to a VM to isolate it (and pi-vpn with wireguard) from the rest of my setup. I tried it with docker and had some network issues I couldn't figure out with my vpn.

**Comment by bcurran3** [comment]
@nicpayne713 - Ha! Me too. I moved pihole (using diet-pi and love it) to a VM on an ESXI server that gets rebooted a lot less than my ansible-nas server (Linux kernals seem to come out every week now days).

I did fix the routing issue I had with the container, but I don't remember what it was since it was a long time ago. Here's what mine looked like:

```
###
### WireGuard
###
wireguard:enabled: true
wireguard_available_externally: "true"
wireguard_traefik_whitelist: "{{ wan }}"
wireguard_data_directory: "{{ docker_home }}/wireguard"
wireguard_env_serverurl: "wireguard.{{ ansible_nas_domain }}"
wireguard_env_peers: "5"
wireguard_env_peerdns: "auto"
wireguard_env_internalsubnet: "10.13.13.0"
wireguard_env_allowedips: "0.0.0.0/0"
wireguard_port: "51820"
wireguard_user_id: "1000"
wireguard_group_id: "1000"
```
```
---
- name: WireGuard Container
  docker_container:
    name: wireguard
    image: linuxserver/wireguard
    pull: true
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ wireguard_user_id }}"
      PGID: "{{ wireguard_group_id }}"
      SERVERURL: "{{ wireguard_env_serverurl }}"
      SERVERPORT: "{{ wireguard_port }}"
      PEERS: "{{ wireguard_env_peers }}"
      PEERDNS: "{{ wireguard_env_peerdns }}"
      INTERNAL_SUBNET: "{{ wireguard_env_internalsubnet }}"
      ALLOWEDIPS: "{{ wireguard_env_allowedips }}"
    volumes:
      - "{{ wireguard_data_directory }}/config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "{{ wireguard_port }}: 51820/udp"
    dns_servers: "{{ ansible_nas_dns }}"
    hostname: "wireguard"
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls: "net.ipv4.conf.all.src_valid_mark=1"
    restart_policy: unless-stopped
    memory: 1g
```
You're probably not going to change your method but maybe someone else without multiple servers and a need will find this useful.

Though I now use wireguard on my diet-pi VM I still keep the container running on my ansible-nas server as a backup. I can then just change the port forwarding on my router (which I can do remotely) to use the backup.
